#!/bin/bash
# script must be executed from root git directory

{ cat src/server/local_deps.txt; echo; } | while read line; do rm -r "src/server/$line"; done

# remove files under server/server that has been generated by npm build and copied from client/build
# cut command remove "./" included in find command result
cd src/client/build
for i in $(find -type f | cut -c 3-)
do
    rm ../../server/server/"$i"
done
cd ../../..
