#!/bin/sh
#Copy this file in .git/hooks/ folder of this repo so it is executed
#before each commit

#Reformat staged python files (exclude deleted ones) to follow pep8 guidelines
PYTHON_FILES_STAGED=$(git diff --name-status --cached | grep '**\.py$' | awk '$1 != "D" { print $2 }')
if [ -n "$PYTHON_FILES_STAGED" ]; then
	autopep8 -i --max-line-length 125 $PYTHON_FILES_STAGED
	git add $PYTHON_FILES_STAGED
fi
